### ISSUE TITLE
Throw error on process exit code !== 0

### ISSUE THREAD

**Issue by matheo** [johnny-mh/rxjs-shell#11]
Hi again @johnny-mh 
I just want to ask you if `spawn` throws an error if the process exists with code !== 0

Looking at my CI log, it seems that the spawned processes can end with an exception and it's not reported to my main subscription.

Have a great weekend!

**Comment by johnny-mh** [comment]
Hi @matheo ~

Some scripts do not end with exit code upper 1.

Seems like your script does not completed with Non-Zero exit code. hard to throw `ShellError` because of `null` passed `err` of callback.

https://www.tldp.org/LDP/abs/html/exit-status.html

Some shell script are not completed with Non-Zero code. they just emit error message stream to `stderr` or `stdout` 😢. I seeing this issue with using `tslint` before.

Please check your spawned process completed without Non-Zero code. and error message emitted to `stderr` or `stdout`. If the script do that. you need to pattern check error message and throwing error manually.

And that case. Do you think it would be convenient if you provided the checking function?

```ts
spawn('ls', '-al')
  .pipe(throwIf(/ERROR:/gi))  // check stdout, stderr

spawn('ls', '-al')
  .pipe(throwIfStdout(/ERROR:/gi))  // check stdout only

spawn('ls', '-al')
  .pipe(throwIfStderr(/ERROR:/gi))  // check stderr only
```

**Comment by matheo** [comment]
@johnny-mh indeed, the standard is not respected always by some scripts.

And now I realize that the problem has to do with my CI plan, because it doesn't stops when the `npm script` exits with non-zero code.

The operators are a nice idea tho!
I could interrupt the stream if I get a `npm ERR!` :)

**Comment by johnny-mh** [comment]
I created PR. Please review that freely if you want. It will be publishing v2.0.0 in 8 hours. Thanks @matheo!

**Comment by matheo** [comment]
Great high-quality stuff! thanks @johnny-mh
